const levels = [
  { xp: 100, grade: "Bouli Bouli" },
  { xp: 125, grade: "Bouli Bouli" },
  { xp: 144, grade: "Bouli Bouli" },
  { xp: 158, grade: "Bouli Bouli" },
  { xp: 170, grade: "Bouli Bouli" },
  { xp: 181, grade: "Bouli Bouli" },
  { xp: 191, grade: "Bouli Bouli" },
  { xp: 200, grade: "Bouli Bouli" },
  { xp: 208, grade: "Bouli Bouli" },
  { xp: 215, grade: "Loukoum" },
  { xp: 222, grade: "Loukoum" },
  { xp: 228, grade: "Loukoum" },
  { xp: 235, grade: "Loukoum" },
  { xp: 241, grade: "Loukoum" },
  { xp: 246, grade: "Loukoum" },
  { xp: 251, grade: "Loukoum" },
  { xp: 257, grade: "Loukoum" },
  { xp: 262, grade: "Loukoum" },
  { xp: 266, grade: "Bien mais pas top" },
  { xp: 271, grade: "Bien mais pas top" },
  { xp: 275, grade: "Bien mais pas top" },
  { xp: 280, grade: "Bien mais pas top" },
  { xp: 284, grade: "Bien mais pas top" },
  { xp: 288, grade: "Bien mais pas top" },
  { xp: 292, grade: "Bien mais pas top" },
  { xp: 296, grade: "Bien mais pas top" },
  { xp: 300, grade: "Bien mais pas top" },
  { xp: 303, grade: "Bien mais pas top" },
  { xp: 307, grade: "Bien mais pas top" },
  { xp: 310, grade: "Ah! On y vient" },
  { xp: 314, grade: "Ah! On y vient" },
  { xp: 317, grade: "Ah! On y vient" },
  { xp: 320, grade: "Ah! On y vient" },
  { xp: 323, grade: "Ah! On y vient" },
  { xp: 327, grade: "Ah! On y vient" },
  { xp: 330, grade: "Ah! On y vient" },
  { xp: 333, grade: "Ah! On y vient" },
  { xp: 336, grade: "Ah! On y vient" },
  { xp: 339, grade: "Ah! On y vient" },
  { xp: 341, grade: "Paladin neutre" },
  { xp: 344, grade: "Paladin neutre" },
  { xp: 347, grade: "Paladin neutre" },
  { xp: 350, grade: "Paladin neutre" },
  { xp: 353, grade: "Paladin neutre" },
  { xp: 355, grade: "Paladin neutre" },
  { xp: 358, grade: "Paladin neutre" },
  { xp: 360, grade: "Paladin neutre" },
  { xp: 363, grade: "Paladin neutre" },
  { xp: 365, grade: "Paladin neutre" },
  { xp: 368, grade: "Poulet" },
  { xp: 370, grade: "Poulet" },
  { xp: 373, grade: "Poulet" },
  { xp: 375, grade: "Poulet" },
  { xp: 377, grade: "Poulet" },
  { xp: 380, grade: "Poulet" },
  { xp: 382, grade: "Poulet" },
  { xp: 384, grade: "Poulet" },
  { xp: 387, grade: "Poulet" },
  { xp: 389, grade: "Poulet" },
  { xp: 391, grade: "En cannes" },
  { xp: 393, grade: "En cannes" },
  { xp: 395, grade: "En cannes" },
  { xp: 397, grade: "En cannes" },
  { xp: 400, grade: "En cannes" },
  { xp: 402, grade: "En cannes" },
  { xp: 404, grade: "En cannes" },
  { xp: 406, grade: "En cannes" },
  { xp: 408, grade: "En cannes" },
  { xp: 410, grade: "En cannes" },
  { xp: 412, grade: "Patron du game" },
  { xp: 414, grade: "Patron du game" },
  { xp: 416, grade: "Patron du game" },
  { xp: 417, grade: "Patron du game" },
  { xp: 419, grade: "Patron du game" },
  { xp: 421, grade: "Patron du game" },
  { xp: 423, grade: "Patron du game" },
  { xp: 425, grade: "Patron du game" },
  { xp: 427, grade: "Patron du game" },
  { xp: 429, grade: "Patron du game" },
  { xp: 430, grade: "Monte Cristo" },
  { xp: 432, grade: "Monte Cristo" },
  { xp: 434, grade: "Monte Cristo" },
  { xp: 436, grade: "Monte Cristo" },
  { xp: 437, grade: "Monte Cristo" },
  { xp: 439, grade: "Monte Cristo" },
  { xp: 441, grade: "Monte Cristo" },
  { xp: 443, grade: "Monte Cristo" },
  { xp: 444, grade: "Monte Cristo" },
  { xp: 446, grade: "Monte Cristo" },
  { xp: 448, grade: "Meilleure version de moi même" },
  { xp: 449, grade: "Meilleure version de moi même" },
  { xp: 451, grade: "Meilleure version de moi même" },
  { xp: 453, grade: "Meilleure version de moi même" },
  { xp: 454, grade: "Meilleure version de moi même" },
  { xp: 456, grade: "Meilleure version de moi même" },
  { xp: 457, grade: "Meilleure version de moi même" },
  { xp: 459, grade: "Meilleure version de moi même" },
  { xp: 461, grade: "Meilleure version de moi même" },
  { xp: 462, grade: "Meilleure version de moi même" }
];